### ISSUE TITLE
EnterpriseTermPicker loading children under wrong nodes.

### ISSUE THREAD

**Issue by gbminnock** [SharePoint/sp-dev-fx-property-controls#156]
Hi I am have some issues with the terms. They seem not to be loading correctly. The children seem to be sorted but are not attached to the correct parents.

Thanks,
Gary

#### Category
- [ ] Bug

#### Version

Please specify what version of the library you are using: [    1.14.0     ]

_If you are not using the latest release, please update and see if the issue is resolved before submitting an issue._

#### Expected / Desired Behavior / Question
Expected terms to load under correct parent.

#### Observed Behavior
All terms are loading but it seems that this child terms are sorted (irrespective of parent) and then are attached to the incorrect parent.

#### Steps to Reproduce
Setup as per instructions. Here are the  properties I use:
`````
PropertyFieldEnterpriseTermPicker('terms', {
                  label: 'Select terms',
                  panelTitle: 'Select terms',
                  allowMultipleSelections: false,
                  excludeSystemGroup: true,
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  properties: this.properties,
                  context: this.context,
                  onGetErrorMessage: null,
                  deferredValidationTime: 0,
                  limitByGroupNameOrID: 'Planes',
                  key: 'termSetsPickerFieldId',
                  includeLabels: true,
                  isTermSetSelectable: true,
                  hideTermStoreName: true
                })
`````

**Comment by AJIXuMuK** [comment]
Hi @gbminnock,
Could you please provide screenshots of how the component’s tree is rendered and how the hierarchy looks at Term Management Store?

**Comment by estruyf** [comment]
@gbminnock this is probably related to: #153. I already implemented a fix for this. You can verify it yourself by installing the latest beta version. More information how you can install the latest beta can be found here: https://sharepoint.github.io/sp-dev-fx-property-controls/beta/

**Comment by gbminnock** [comment]
Hi @AJIXuMuK & @estruyf, 

I've installed the beta release this morning but am still seeing the same issue. 
**version**   
`"@pnp/spfx-property-controls": "1.14.1-beta.db31aed"`
**pnp version** 
````
  "@pnp/common": "^1.2.8",
    "@pnp/logging": "^1.2.8",
    "@pnp/odata": "^1.2.8",
    "@pnp/sp": "^1.2.8",
    "@pnp/sp-clientsvc": "^1.2.8",
    "@pnp/sp-taxonomy": "^1.2.8",
````
I have copied the test case provided by the user in #153. 

#### term store management
![image](https://user-images.githubusercontent.com/2708345/52552594-c0a90900-2dd8-11e9-9eb8-f4f9bb6b1f86.png)

#### webpart
![image](https://user-images.githubusercontent.com/2708345/52552601-c6065380-2dd8-11e9-875c-0278b5101524.png)

Tks, 
Gary

**Comment by estruyf** [comment]
@gbminnock overlooked the enterprise part, so it could indeed be that the issue needs to be also fixed on that one.

**Comment by estruyf** [comment]
@gbminnock implemented the fix, and the new beta version is available. Could you please verify if it fixes the issue on your end?

**Comment by gbminnock** [comment]
@estruyf yes its working fine now. Tks
![image](https://user-images.githubusercontent.com/2708345/52634572-777fb480-2ebf-11e9-8f5e-4edccfca31a6.png)

**Comment by estruyf** [comment]
Thanks for verifying!

**Comment by estruyf** [comment]
A new version is building at the moment. This fix will be available in version `1.14.1`.
